#!/bin/bash

basePath="/root/Pictures/timelapse2/"

nb_pics=$1
delay=$2

for (( c=1; c<=$nb_pics; c++ )); do
    echo "Starting cycle $i"
    date=$(date +'%Y%m%d%H%M%S%N')
    path="${basePath}pic${date}.jpg"
    echo $path
    fswebcam --no-banner ${path}
    sleep $delay
done
